[package]
name = "sysy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
koopa = "0.0.7"
lalrpop-util = { version = "0.20.2", features = ["lexer"] }
lazy_static = "1.4.0"

[build-dependencies]
lalrpop = "0.20.2"
